name: Publish Backend To Docker

on:
  push:
    branches:
      - master
    paths:
      - apps/backend/**
  workflow_dispatch:

jobs:
  docker:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-docker]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - name: Login to Quay Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: build the image
        run: |
          docker buildx build --push \
            --tag ghcr.io/riddea/backend:latest \
            --tag ghcr.io/riddea/backend:${{ github.sha }} \
            --tag quay.io/riddea/backend:latest \
            --tag quay.io/riddea/backend:${{ github.sha }} \
            --target backend \
            --platform linux/amd64,linux/arm64 .
      - name: Deploy To CapRover
        uses: floms/action-caprover@v1
        with:
          host: ${{ secrets.CAPPROVER_DOMAIN }}
          password: ${{ secrets.CAPROVER_PASSWORD }}
          app: riddea-backend
          image: quay.io/riddea/backend
