name: Publish Api To Docker

on:
  push:
    branches:
      - master

jobs:
  docker:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-docker]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Quay Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          target: api
          push: true
          tags: |
            ghcr.io/riddea/api:latest
            ghcr.io/riddea/api:${{ github.sha }}
            quay.io/riddea/api:latest
            quay.io/riddea/api:${{ github.sha }}
      - name: Deploy To CapRover
        uses: floms/action-caprover@v1
        with:
          host: ${{ secrets.CAPPROVER_DOMAIN }}
          password: ${{ secrets.CAPROVER_PASSWORD }}
          app: riddea-api
          image: quay.io/riddea/api
